version: '3'
services:
  pg:
    image: postgres:11-alpine
    ports:
      - "32770:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
